---

- name: Generate a random Nickname for the bridge
  shell: grep -v -P "[\x80-\xFF]" /usr/share/dict/american-english-huge | sed -e "s/'//" | shuf -n 2 | xargs | sed -e 's/ //' | cut -c 1-16 > {{ tor_bridge_nickname_file }}
  args:
    creates: "{{ tor_bridge_nickname_file }}"

- name: Generate the Markdown Tor instructions
  template:
    src: instructions.md.j2
    dest: "{{ tor_markdown_instructions }}"

- name: Convert the Markdown Tor instructions into HTML and surround them with the header and footer template
  shell: markdown {{ tor_markdown_instructions }} | cat {{ streisand_header_template }} - {{ streisand_footer_template }} > {{ tor_html_instructions }}
